# Generated by Django 3.0.4 on 2020-03-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('email_id', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientHist',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eradicate.Patient')),
                ('diabetes', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with Diabetes?')),
                ('diabetes_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with Diabetes?')),
                ('hypertension', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with Hypertension?')),
                ('hypertension_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with Hypertension?')),
                ('obesity', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Are you obese?')),
                ('obesity_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been Obese?')),
                ('pcod', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with PCOD/PCOS (Females Only)?')),
                ('pcod_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with PCOD/PCOS (Females Only)?')),
                ('thyroid', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with Thyroid problems?')),
                ('thyroid_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with Thyroid problems?')),
                ('heartdiease', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with Heart desease?')),
                ('heartdiease_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with Heart desease?')),
                ('liverdisease', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with Liver desease?')),
                ('liverdisease_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with Liver desease?')),
                ('kidney', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you ever been diagnosed with Kidney desease?')),
                ('kidney_long', models.CharField(blank=True, max_length=20, verbose_name='If Yes, how long have you been diagnosed with Kidney desease?')),
                ('familyhistory', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you have a history of Diabetes in your family?')),
                ('currentmed', models.CharField(blank=True, max_length=70, verbose_name='Current Medications: ')),
                ('foodhabit', models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg')], default='V', max_length=1, verbose_name='What are your food habits?')),
                ('hba1c', models.FloatField(max_length=20, verbose_name='HBA1C results: ')),
                ('fasting', models.FloatField(max_length=20, verbose_name='Your fasting blood sugar results: ')),
                ('pp', models.FloatField(max_length=20, verbose_name='Your PP results: ')),
            ],
            bases=('eradicate.patient',),
        ),
    ]
